-- 0. Tipos de datos personalizados
CREATE TYPE rol_usuario AS ENUM ('admin', 'cliente');

-- 1. Categorías
CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  descripcion TEXT
);

-- 2. Productos (Producto Final)
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  stock_actual INT DEFAULT 0,
  descripcion TEXT,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL
);

CREATE TABLE producto_imagenes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE NOT NULL,
  url TEXT NOT NULL,
  es_principal BOOLEAN DEFAULT false,
  orden INT NOT NULL,
  fecha_subida TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Restricción: Un producto no puede tener dos imágenes con el mismo número de orden
  CONSTRAINT unique_producto_orden UNIQUE(producto_id, orden)

    -- Restricción: Un producto no puede tener la misma imagen
  CONSTRAINT unique_producto_url UNIQUE(producto_id, url)
);

-- 3. Ingredientes / Insumos (Lo que se usa para cocinar)
CREATE TABLE ingredientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  stock_actual DECIMAL(10,2) DEFAULT 0,
  unidad_id BIGINT REFERENCES unidades_medida(id)
  ALTER TABLE ingredientes ADD COLUMN es_ilimitado BOOLEAN DEFAULT FALSE;
);

CREATE TABLE unidades_medida (
    id SERIAL PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,     -- Ej: 'Kilogramos'
    abreviatura TEXT NOT NULL UNIQUE -- Ej: 'kg'
);

-- Insertamos las unidades básicas profesionales
INSERT INTO unidades_medida (nombre, abreviatura) VALUES
('Gramos', 'g'),
('Kilogramos', 'kg'),
('Mililitros', 'ml'),
('Litros', 'l'),
('Unidades', 'u'),
('Docenas', 'doc');

-- Recetas (Relación entre Productos e Ingredientes)
CREATE TABLE producto_ingredientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE NOT NULL,
  ingrediente_id BIGINT REFERENCES ingredientes(id) ON DELETE CASCADE NOT NULL,
  cantidad_necesaria DECIMAL(10, 4) NOT NULL CHECK (cantidad_necesaria > 0),

  -- Restricción: Un mismo ingrediente no puede aparecer dos veces en el mismo producto
  CONSTRAINT unique_receta_item UNIQUE(producto_id, ingrediente_id)
);

-- 4. Proveedores
CREATE TABLE proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  contacto_nombre TEXT,
  telefono TEXT,
  email TEXT
);

-- 5. Entradas de Inventario (Registro de compras de ingredientes)
-- La Cabecera: El resumen de la compra
CREATE TABLE compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE RESTRICT NOT NULL,
  fecha_compra TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  monto_total DECIMAL(10,2) DEFAULT 0,
  notas TEXT
);

-- El Detalle: Cada producto dentro de ese ticket
CREATE TABLE compra_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id BIGINT REFERENCES compras(id) ON DELETE CASCADE NOT NULL,
  ingrediente_id BIGINT REFERENCES ingredientes(id) ON DELETE RESTRICT NOT NULL,
  cantidad DECIMAL(10,2) NOT NULL CHECK (cantidad > 0),
  precio_unitario DECIMAL(10,2) NOT NULL CHECK (precio_unitario >= 0)
);

-- 6. Perfiles
CREATE TABLE perfiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  rol rol_usuario DEFAULT 'cliente',
  direccion TEXT,
  telefono TEXT NOT NULL,
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
  activo BOOLEAN DEFAULT TRUE,
  eliminado_el TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

-- 7. Estados del Pedido (Catálogo/Relleno)
CREATE TABLE estados_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE 
);

-- 8. Cupones / Promociones
CREATE TABLE cupones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  descuento_porcentaje INT CHECK (descuento_porcentaje > 0 AND descuento_porcentaje <= 100),
  activo BOOLEAN DEFAULT true,
  fecha_expiracion DATE
);

-- 9. Pedidos
CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id UUID REFERENCES perfiles(id) NOT NULL, -- Relación con el perfil del cliente
  fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  total DECIMAL(10,2) DEFAULT 0,
  estado_id BIGINT REFERENCES estados_pedido(id) DEFAULT 1,
  cupon_id BIGINT REFERENCES cupones(id) ON DELETE SET NULL
);

-- 10. Detalle de Pedido (Relación Muchos a Muchos entre Pedidos y Productos)
CREATE TABLE detalle_pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE,
  producto_id BIGINT REFERENCES productos(id),
  cantidad INT NOT NULL,
  precio_unitario_historico DECIMAL(10,2) NOT NULL 
);

/* Modificaciones Pendientes a las tablas */
ALTER TABLE categorias 
ADD COLUMN activo BOOLEAN DEFAULT TRUE;

-- Índice para mejorar rendimiento de filtros
CREATE INDEX idx_categorias_activo ON categorias(activo);

-- Agregar campos para adelanto configurable
ALTER TABLE productos 
ADD COLUMN requiere_adelanto BOOLEAN DEFAULT FALSE,
ADD COLUMN porcentaje_adelanto INTEGER DEFAULT 50 CHECK (porcentaje_adelanto > 0 AND porcentaje_adelanto <= 100);

-- Ejemplo: Marcar categoría de queques personalizados con adelanto del 50%
UPDATE productos 
SET requiere_adelanto = TRUE,
    porcentaje_adelanto = 50
WHERE categoria_id = (SELECT id FROM categorias WHERE nombre = 'Queques Personalizados');

-- Si se quiere que un producto específico tenga adelanto diferente (ej: 30%) entonces hay que hacer
-- UPDATE productos SET porcentaje_adelanto = 30 WHERE id = X;

/* Tabla pedidos - Agregar columnas para control de pagos */
-- Agregar campos de control de pago
ALTER TABLE pedidos 
ADD COLUMN requiere_adelanto BOOLEAN DEFAULT FALSE,
ADD COLUMN porcentaje_adelanto INTEGER DEFAULT 50,
ADD COLUMN monto_adelanto DECIMAL(10,2) DEFAULT 0,
ADD COLUMN monto_pagado DECIMAL(10,2) DEFAULT 0,
ADD COLUMN monto_pendiente DECIMAL(10,2) DEFAULT 0,
ADD COLUMN pago_completo BOOLEAN DEFAULT FALSE;

-- Actualizar pedidos existentes para que sean compatibles
UPDATE pedidos 
SET pago_completo = TRUE,
    monto_pagado = total,
    monto_pendiente = 0
WHERE estado_id >= 2; -- Los que ya están confirmados o más avanzados

/* C. Tabla estados_pedido - Agregar nuevo estado */

-- Agregar estado para pedidos con pago parcial
INSERT INTO estados_pedido (nombre) 
VALUES ('Pago Parcial')
ON CONFLICT (nombre) DO NOTHING;
-- Debería quedar:
-- 1 = Pendiente de Pago
-- 2 = Confirmado (pago completo)
-- 3 = En Producción
-- 4 = Listo para Retiro
-- 5 = Entregado
-- 6 = Cancelado
-- 7 = Pago Parcial 

ALTER TABLE productos 
ADD COLUMN activo BOOLEAN DEFAULT true;